version: '3'

services:
  app:
    build: .
    restart: always
    working_dir: /app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ".:/app"
    depends_on:
      - db
  db:
    image: postgres:14.2-alpine
    restart: always
    env_file:
      - .env
    expose:
      - "5432"
    ports:
      - "5431:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  app:
  db:
