version: '3'

services:
  app:
    build:
      context: .
      dockerfile: api.Dockerfile
    restart: always
    working_dir: /app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ".:/app"
    depends_on:
      - db
  client:
    build:
      context: .
      dockerfile: react.Dockerfile
    restart: always
    working_dir: /client
    ports:
      - "3000:3000"
    volumes:
      - "./src/Business_Assistant_Client/:/client"
    depends_on:
      - db
      - app
  db:
    image: postgres:14.2-alpine
    restart: always
    env_file:
      - .env
    expose:
      - "5432"
    ports:
      - "5431:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  app:
  db:
  client:
